name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.5'
        cache-dependency-path: ./backend/go.sum

    - name: Install dependencies
      run: go mod download

    - name: Run Tests
      run: go test ./internal/usecase/... -v -coverprofile=coverage.out

    - name: Coverage Report
      run: go tool cover -func=coverage.out
